Repository Ravi-Joshi-22/Major-Project, pull requests merged in 2018-03, with the labels that each got.

#121 Applied Openings Integration
  client/src/actions/interviewee/index.js
  client/src/actions/interviewee/types.js
  client/src/components/userDashboard/AppliedOpenings/currentTable.js
  client/src/components/userDashboard/AppliedOpenings/givenTable.js
  client/src/components/userDashboard/AppliedOpenings/pendingTable.js
  client/src/components/userDashboard/AppliedOpenings/upcomingTable.js
  client/src/components/userDashboard/Home/elligibleOpenings.js
  client/src/components/userDashboard/Home/elligibleTable.js
  client/src/components/userDashboard/appliedOpenings.js
  client/src/components/userDashboard/home.js
  client/src/components/userDashboard/userDrawer.js
  client/src/reducers/interviewee/openingReducer.js
  lib/interviewee/opening.js
Labels: Review Required

#122 to get all the openings of company
  app/controllers/company/opening.js
  lib/company/opening.js
Labels: Review Required

#125 Company Dashboard can now be successfully used with analytics
  app/controllers/company/custom.js
  app/helpers/populate.js
  config/constants.js
  lib/company/custom.js
Labels: Backend

#126 [UI] Modal addition
  client/src/components/IntervieweeRegister/Certification.js
  client/src/components/IntervieweeRegister/Courses.js
  client/src/components/IntervieweeRegister/Graduation.js
  client/src/components/IntervieweeRegister/Internship.js
  client/src/components/IntervieweeRegister/Jobs.js
  client/src/components/IntervieweeRegister/Project.js
  client/src/components/IntervieweeRegister/Secondary.js
  client/src/components/IntervieweeRegister/SeniorSecondary.js
  client/src/components/IntervieweeRegister/Skills.js
  client/src/components/IntervieweeRegister/Test.js
  client/src/components/userProfile/courses.js
  client/src/components/userProfile/education.js
  client/src/components/userProfile/experience.js
  client/src/components/userProfile/modalOpening/courseModal.js
  client/src/components/userProfile/modalOpening/eduModal.js
  client/src/components/userProfile/modalOpening/expmodal.js
  client/src/components/userProfile/percentage.js
  client/src/components/userProfile/personal.js
  client/src/components/userProfile/projects.js
  client/src/components/userProfile/skills.js
  client/src/pages/userProfile/index.js
Labels: Frontend

#133 Openings are viewed in company dashboard
  client/src/components/companyDashboard/DrawerArea/viewOpenings/detailsPage.js
  client/src/components/companyDashboard/DrawerArea/viewOpenings/openingsCard.js
  client/src/components/companyDashboard/DrawerArea/viewOpenings/settingsListCard.js
  client/src/components/companyDashboard/NavDrawer.js
  client/src/pages/app.js
  client/src/pages/viewOpenings/index.css
  client/src/pages/viewOpenings/index.js
Labels: Review Required

#138 Delete Opening API Integrated
  client/src/actions/company/index.js
  client/src/actions/company/types.js
  client/src/components/companyDashboard/DrawerArea/viewOpenings/openingsCard.js
Labels: Review Required
