Repository Ravi-Joshi-22/Major-Project, pull requests merged in 2018-04, with the labels that each got.

#146 View Results of an opening
  app/controllers/company/opening.js
  app/helpers/question_helper.js
  lib/company/opening.js
Labels: Backend

#153 Selection rejection mails
  app/controllers/company/opening.js
  app/controllers/interviewee/opening.js
  app/helpers/mail_helper.js
  config/dev.js
  lib/company/opening.js
  lib/interviewee/opening.js
  templates/applied/html.ejs
  templates/applied/subject.txt
  templates/rejection/html.ejs
  templates/rejection/subject.txt
  templates/selection/html.ejs
  templates/selection/subject.txt
Labels: Backend

#171 Interviewee Result Display
  client/src/actions/interviewee/index.js
  client/src/actions/interviewee/types.js
  client/src/components/userDashboard/Result/GridView.js
  client/src/components/userDashboard/Result/scoreCard.js
  client/src/components/userProfile/UserDetailsForm/Graduation.js
  client/src/components/userProfile/UserDetailsForm/Internship.js
  client/src/components/userProfile/UserDetailsForm/Jobs.js
  client/src/components/userProfile/UserDetailsForm/Project.js
  client/src/components/userProfile/courses.js
  client/src/components/userProfile/education.js
  client/src/components/userProfile/experience.js
  client/src/components/userProfile/personal.js
  client/src/components/userProfile/projects.js
  client/src/components/userProfile/skillchips.js
  client/src/pages/app.js
  client/src/pages/viewResultInterviewee/index.js
  client/src/reducers/openingReducer.js
  config/dev.js
Labels: Do not merge

#167 Experience and Education data are displayed systematically
  client/src/components/userProfile/UserDetailsForm/Graduation.js
  client/src/components/userProfile/UserDetailsForm/Internship.js
  client/src/components/userProfile/UserDetailsForm/Jobs.js
  client/src/components/userProfile/UserDetailsForm/Project.js
  client/src/components/userProfile/courses.js
  client/src/components/userProfile/education.js
  client/src/components/userProfile/experience.js
  client/src/components/userProfile/personal.js
  client/src/components/userProfile/projects.js
  client/src/components/userProfile/skillchips.js
  config/dev.js
Labels: Do not merge

#166 Company Result Page
  client/public/Assets/workIcon.png
  client/src/actions/company/index.js
  client/src/actions/company/types.js
  client/src/components/companyDashboard/CompanyResult.js
  client/src/components/companyDashboard/DrawerArea/InterviewOpening.js
  client/src/components/companyDashboard/DrawerArea/viewOpenings/detailsPage.js
  client/src/components/companyDashboard/DrawerArea/viewOpenings/openingsCard.js
  client/src/components/companyDashboard/DrawerArea/viewOpenings/settingsListCard.js
  client/src/components/companyDashboard/MainArea.js
  client/src/components/companyDashboard/NavDrawer.js
  client/src/components/companyDashboard/companyResult/hireDialog.js
  client/src/components/companyDashboard/companyResult/openingDetailCard.js
  client/src/components/companyDashboard/companyResult/openingResultCard.js
  client/src/components/companyDashboard/viewOpenings/openingsCard.js
  client/src/components/companyDashboard/viewOpeningsMainPage.js
  client/src/components/login/Login.js
  client/src/components/userProfile/percentage.js
  client/src/pages/companyDashboard/index.js
  client/src/pages/companyRegister/index.js
  client/src/reducers/app/modalReducer.js
  client/src/reducers/openingReducer.js
Labels: Do not merge

#178 Company Result Page
  client/src/actions/company/index.js
  client/src/actions/company/types.js
  client/src/components/companyDashboard/CompanyResult.js
  client/src/components/companyDashboard/DrawerArea/viewOpenings/detailsPage.js
  client/src/components/companyDashboard/DrawerArea/viewOpenings/openingsCard.js
  client/src/components/companyDashboard/DrawerArea/viewOpenings/settingsListCard.js
  client/src/components/companyDashboard/NavDrawer.js
  client/src/components/companyDashboard/companyResult/hireDialog.js
  client/src/components/companyDashboard/companyResult/openingDetailCard.js
  client/src/components/companyDashboard/companyResult/openingResultCard.js
  client/src/components/companyDashboard/viewOpenings/openingsCard.js
  client/src/components/companyDashboard/viewOpeningsMainPage.js
  client/src/components/login/Login.js
  client/src/components/userDashboard/UserDrawer/profileAvatar.js
  client/src/components/userDashboard/userDrawer.js
  client/src/pages/app.js
  client/src/pages/companyDashboard/index.js
  client/src/pages/login/index.js
  client/src/reducers/app/modalReducer.js
  client/src/reducers/openingReducer.js
Labels: Frontend, Review Required

#180 Logout API Integration
  client/src/actions/app/index.js
  client/src/components/companyDashboard/Dropdown.js
  client/src/components/companyDashboard/NavDrawer.js
  client/src/components/companyDashboard/Title.js
  client/src/components/userDashboard/userDrawer.js
  client/src/pages/companyDashboard/index.js
Labels: Review Required

#184 User Tables Enhanced
  client/src/actions/app/index.js
  client/src/components/userDashboard/AppliedOpenings/currentTable.js
  client/src/components/userDashboard/AppliedOpenings/upcomingTable.js
  client/src/components/userDashboard/Home/elligibleOpenings.js
Labels: Frontend, Review Required
